const String imageUrl = "https://i.pravatar.cc/150?img=";
const String firstName = "First Name";
const String lastName = "Last Name";
const String createNew = "Create New";
const String update = "Update";
const String mobileNumber = "Mobile Number";
const String addNewContact = "Add New Contacts";
const String fixEmailUser = "vishalkajales@gmail.com";
const String contactsHeading = "Contacts";
const String searchContacts = "Search contacts";
const String delete = "DELETE";
const String myContacts = "MY CONTACTS";
const String mobile = "Mobile";
const String contactInfo = "Contact Info";
const String countryCode = "+91";
const String contactNumberValidator = "Pleas enter valid contact Number!";
const String nameValidator = "Pleas enter valid name!";
